In [5]:
import pandas as pd
import numpy as np
import re
import nltk

cv_df = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\NLP Project\Dataset\cv.csv")
job_df = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\NLP Project\Dataset\job.csv")
matches_df = pd.read_csv(r"C:\Users\ASUS\OneDrive\Desktop\NLP Project\Dataset\matches.csv")

print("Datasets loaded successfully!")

Datasets loaded successfully!

In [6]:
print("CV Dataset Shape:", cv_df.shape)
print("Job Dataset Shape:", job_df.shape)
print("Matches Dataset Shape:", matches_df.shape)

CV Dataset Shape: (9544, 11)
Job Dataset Shape: (1167, 10)
Matches Dataset Shape: (122560, 13)

In [7]:
print("===== CV DATASET =====")
display(cv_df.head())

print("===== JOB DATASET =====")
display(job_df.head())

print("===== MATCHES DATASET =====")
display(matches_df.head())

===== CV DATASET =====

,candidate_id,source_row,target_position,resume_text,clean_skills,clean_skills_json,education_text,experience_text,years_experience,inferred_category,embedding
0,cand_00000,0,Senior Software Engineer,Target position: Senior Software Engineer Obje...,"[""big data"", ""hadoop"", ""hive"", ""python"", ""mapr...","[""big data"", ""hadoop"", ""hive"", ""python"", ""mapr...",['B.Tech'] ['Electronics'] ['The Amity School ...,At least 1 year ['Big Data Analyst'] Technical...,1.0,INFORMATION-TECHNOLOGY,"[0.06282798945903778, 0.03344276547431946, -0...."
1,cand_00001,1,Machine Learning (ML) Engineer,Target position: Machine Learning (ML) Enginee...,"[""data analysis"", ""data analytics"", ""business ...","[""data analysis"", ""data analytics"", ""business ...","['B.Sc (Maths)', 'M.Sc (Science) (Statistics)'...",At least 5 year(s) ['Business Analyst'] Machin...,5.0,INFORMATION-TECHNOLOGY,"[0.038818471133708954, 0.016407284885644913, -..."
2,cand_00002,2,"Executive/ Senior Executive- Trade Marketing, ...",Target position: Executive/ Senior Executive- ...,"[""software development"", ""machine learning"", ""...","[""software development"", ""machine learning"", ""...",['B.Tech'] ['Electronics/Telecommunication'] [...,At least 3 years ['Software Developer (Machine...,3.0,INFORMATION-TECHNOLOGY,"[0.05784870311617851, 0.004059996455907822, -0..."
3,cand_00003,3,Business Development Executive,Target position: Business Development Executiv...,"[""accounts payables"", ""accounts receivables"", ...","[""accounts payables"", ""accounts receivables"", ...",['Computer Applications Specialist Certificate...,"1 to 3 years ['Accountant', 'Accounts Receivab...",3.0,FINANCE,"[0.019778592512011528, 0.05583859235048294, -0..."
4,cand_00004,4,Senior iOS Engineer,Target position: Senior iOS Engineer Objective...,"[""analytical reasoning"", ""compliance testing k...","[""analytical reasoning"", ""compliance testing k...",['Bachelor of Business Administration'] ['Acco...,"At least 4 years ['Staff Accountant', 'Senior ...",4.0,FINANCE,"[0.05881429836153984, 0.0753575786948204, -0.0..."

===== JOB DATASET =====

,job_id,job_title,category,job_description,job_text,clean_skills,clean_skills_json,education_text,years_required,embedding
0,3651735073,Director of Finance,FINANCE,APPLY HERE\nHTTPS://WWW.INDEED.COM/JOB/DIRECTO...,Job title: Director of Finance Category: FINAN...,"[""financial management"", ""accounting"", ""gaap p...","[""financial management"", ""accounting"", ""gaap p...",APPLY HERE\nHTTPS://WWW.INDEED.COM/JOB/DIRECTO...,30.0,"[-0.006719283293932676, 0.1176915317773819, -0..."
1,3715891138,Human Resources Manager,HR,HUMAN RESOURCES MANAGER POSITION SUMMARYTHE I...,Job title: Human Resources Manager Category: H...,"[""recruiting"", ""talent management"", ""complianc...","[""recruiting"", ""talent management"", ""complianc...",HUMAN RESOURCES MANAGER POSITION SUMMARYTHE I...,9.0,"[0.07242906838655472, -0.04977822303771973, 0...."
2,3782812525,Salesperson,SALES,THE TERRA FORZA GOLF TEAM IS GROWING! TERRITOR...,Job title: Salesperson Category: SALES Skills:...,"[""sales"", ""customer relationship management"", ...","[""sales"", ""customer relationship management"", ...",THE TERRA FORZA GOLF TEAM IS GROWING! TERRITOR...,3.0,"[0.05193764343857765, -0.01702122576534748, -0..."
3,3861704803,Business Development Manager,BUSINESS-DEVELOPMENT,"HELLO FOLKS,HOPE YOU ARE WELL AND DOING GREAT,...",Job title: Business Development Manager Catego...,"[""account management"", ""client relationship ma...","[""account management"", ""client relationship ma...","HELLO FOLKS,HOPE YOU ARE WELL AND DOING GREAT,...",8.0,"[0.007077623158693314, -0.022816024720668793, ..."
4,3862673730,AOC Human Resources Project Manager,HR,ADMINISTRATIVE OFFICE OF THE COURTSBUSINESS UN...,Job title: AOC Human Resources Project Manager...,"[""project management"", ""human resources admini...","[""project management"", ""human resources admini...",ADMINISTRATIVE OFFICE OF THE COURTSBUSINESS UN...,40.0,"[0.018434137105941772, 0.08029589802026749, -0..."

===== MATCHES DATASET =====

,candidate_id,job_id,final_score,raw_score,label_strength,semantic_score,skill_score,position_score,category_score,experience_score,education_score,candidate_rank,candidate_rank_pct
0,cand_00000,3906246896,0.635354,0.479077,medium_positive,0.867852,0.215161,0.621538,0.0,0.250,1.0,1,1.000000
1,cand_00000,3902931012,0.599043,0.437020,medium_positive,0.775035,0.000000,0.341304,1.0,0.500,1.0,2,0.977099
2,cand_00000,3905214623,0.560359,0.404657,weak_positive,0.766395,0.054937,0.212903,1.0,0.025,1.0,3,0.923664
3,cand_00000,3889743825,0.540995,0.393352,weak_positive,0.821683,0.000000,0.189655,1.0,0.500,0.5,4,0.885496
4,cand_00000,3902357305,0.538510,0.393074,weak_positive,0.764884,0.046768,0.177419,1.0,0.500,0.5,5,0.877863

In [8]:
print("CV Columns:")
print(cv_df.columns.tolist())

print("\nJob Columns:")
print(job_df.columns.tolist())

print("\nMatches Columns:")
print(matches_df.columns.tolist())

CV Columns:
['candidate_id', 'source_row', 'target_position', 'resume_text', 'clean_skills', 'clean_skills_json', 'education_text', 'experience_text', 'years_experience', 'inferred_category', 'embedding']

Job Columns:
['job_id', 'job_title', 'category', 'job_description', 'job_text', 'clean_skills', 'clean_skills_json', 'education_text', 'years_required', 'embedding']

Matches Columns:
['candidate_id', 'job_id', 'final_score', 'raw_score', 'label_strength', 'semantic_score', 'skill_score', 'position_score', 'category_score', 'experience_score', 'education_score', 'candidate_rank', 'candidate_rank_pct']

In [9]:
print("===== CV MISSING VALUES =====")
print(cv_df.isnull().sum())

print("\n===== JOB MISSING VALUES =====")
print(job_df.isnull().sum())

print("\n===== MATCHES MISSING VALUES =====")
print(matches_df.isnull().sum())

===== CV MISSING VALUES =====
candidate_id         0
source_row           0
target_position      0
resume_text          0
clean_skills         0
clean_skills_json    0
education_text       0
experience_text      0
years_experience     0
inferred_category    0
embedding            0
dtype: int64

===== JOB MISSING VALUES =====
job_id               0
job_title            0
category             0
job_description      0
job_text             0
clean_skills         0
clean_skills_json    0
education_text       0
years_required       0
embedding            0
dtype: int64

===== MATCHES MISSING VALUES =====
candidate_id          0
job_id                0
final_score           0
raw_score             0
label_strength        0
semantic_score        0
skill_score           0
position_score        0
category_score        0
experience_score      0
education_score       0
candidate_rank        0
candidate_rank_pct    0
dtype: int64

In [10]:
print("CV duplicate rows:", cv_df.duplicated().sum())
print("Job duplicate rows:", job_df.duplicated().sum())
print("Matches duplicate rows:", matches_df.duplicated().sum())

CV duplicate rows: 0
Job duplicate rows: 0
Matches duplicate rows: 0

In [11]:
print("===== CANDIDATE CATEGORIES =====")
print(cv_df["inferred_category"].value_counts())

print("\n===== JOB CATEGORIES =====")
print(job_df["category"].value_counts())

print("\n===== MATCH LABELS =====")
print(matches_df["label_strength"].value_counts())

===== CANDIDATE CATEGORIES =====
inferred_category
INFORMATION-TECHNOLOGY    8140
FINANCE                   1010
SALES                      215
BUSINESS-DEVELOPMENT        83
HR                          80
UNKNOWN                     16
Name: count, dtype: int64

===== JOB CATEGORIES =====
category
INFORMATION-TECHNOLOGY    240
BUSINESS-DEVELOPMENT      239
FINANCE                   236
SALES                     232
HR                        220
Name: count, dtype: int64

===== MATCH LABELS =====
label_strength
medium_positive    70636
weak_positive      51150
strong_positive      774
Name: count, dtype: int64

In [12]:
print("===== CANDIDATE EXPERIENCE =====")
print(cv_df["years_experience"].describe())

print("\n===== JOB EXPERIENCE REQUIREMENT =====")
print(job_df["years_required"].describe())

===== CANDIDATE EXPERIENCE =====
count    9544.000000
mean        5.545054
std         4.404667
min         0.000000
25%         3.000000
50%         5.000000
75%         8.000000
max        31.000000
Name: years_experience, dtype: float64

===== JOB EXPERIENCE REQUIREMENT =====
count    1167.000000
mean       14.300951
std        12.626580
min         0.000000
25%         4.000000
50%        10.000000
75%        25.000000
max        40.000000
Name: years_required, dtype: float64

In [16]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [17]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
import nltk

stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    if pd.isna(text):
        return ""
    
    # Convert to lowercase
    text = text.lower()
    
    # Remove URLs
    text = re.sub(r"http\S+|www\S+", " ", text)
    
    # Remove special characters and numbers
    text = re.sub(r"[^a-zA-Z\s]", " ", text)
    
    # Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()
    
    # Tokenization
    tokens = nltk.word_tokenize(text)
    
    # Stop-word removal and lemmatization
    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
        if word not in stop_words
    ]
    
    return " ".join(tokens)

In [18]:
sample_resume = cv_df["resume_text"].iloc[0]

print("===== ORIGINAL RESUME =====")
print(sample_resume[:1000])

print("\n===== PREPROCESSED RESUME =====")
print(preprocess_text(sample_resume)[:1000])

===== ORIGINAL RESUME =====
Target position: Senior Software Engineer Objective: Big data analytics working and database warehouse manager with robust experience in handling all kinds of data. I have also used multiple cloud infrastructure services and am well acquainted with them. Currently in search of role that offers more of development. Skills: big data, hadoop, hive, python, mapreduce, spark, java, machine learning, cloud, hdfs, yarn, core java, data science, c++, data structures, dbms, rdbms, informatica, talend, amazon redshift, microsoft azure Education: ['B.Tech'] ['Electronics'] ['The Amity School of Engineering & Technology (ASET), Noida'] B.Sc in Computer Science & Engineering from a reputed university. Experience: At least 1 year ['Big Data Analyst'] Technical Support Troubleshooting Collaboration Documentation System Monitoring Software Deployment Training & Mentorship Industry Trends Field Visits Technical Support Troubleshooting Collaboration Documentation System Monitoring Software Deployment Tr

===== PREPROCESSED RESUME =====
target position senior software engineer objective big data analytics working database warehouse manager robust experience handling kind data also used multiple cloud infrastructure service well acquainted currently search role offer development skill big data hadoop hive python mapreduce spark java machine learning cloud hdfs yarn core java data science c data structure dbms rdbms informatica talend amazon redshift microsoft azure education b tech electronics amity school engineering technology aset noida b sc computer science engineering reputed university experience least year big data analyst technical support troubleshooting collaboration documentation system monitoring software deployment training mentorship industry trend field visit technical support troubleshooting collaboration documentation system monitoring software deployment training mentorship industry trend field visit nov till date

In [19]:
cv_df["processed_resume"] = cv_df["resume_text"].apply(preprocess_text)

job_df["processed_job"] = job_df["job_description"].apply(preprocess_text)

print("Resume preprocessing completed.")
print("Job description preprocessing completed.")

Resume preprocessing completed.
Job description preprocessing completed.

In [20]:
comparison = pd.DataFrame({
    "Original Resume": cv_df["resume_text"].head(5),
    "Processed Resume": cv_df["processed_resume"].head(5)
})

display(comparison)

,Original Resume,Processed Resume
0,Target position: Senior Software Engineer Obje...,target position senior software engineer objec...
1,Target position: Machine Learning (ML) Enginee...,target position machine learning ml engineer o...
2,Target position: Executive/ Senior Executive- ...,target position executive senior executive tra...
3,Target position: Business Development Executiv...,target position business development executive...
4,Target position: Senior iOS Engineer Objective...,target position senior io engineer objective p...

In [21]:
import ast

def extract_skills(skill_text):
    try:
        return ast.literal_eval(skill_text)
    except:
        return []

cv_df["skills_list"] = cv_df["clean_skills"].apply(extract_skills)
job_df["skills_list"] = job_df["clean_skills"].apply(extract_skills)

In [22]:
from collections import Counter

candidate_skills = Counter()

for skills in cv_df["skills_list"]:
    candidate_skills.update(skills)

print("===== TOP 20 CANDIDATE SKILLS =====")

for skill, count in candidate_skills.most_common(20):
    print(skill, ":", count)

===== TOP 20 CANDIDATE SKILLS =====
python : 3900
machine learning : 3696
sql : 2063
data analysis : 1792
java : 1710
deep learning : 1596
excel : 1438
autocad : 1432
sales : 1212
data science : 1092
c++ : 1092
natural language processing : 1092
project management : 1064
data analytics : 1036
artificial intelligence : 980
marketing : 953
accounting : 902
software development : 901
tensorflow : 848
tableau : 840

In [23]:
job_skills = Counter()

for skills in job_df["skills_list"]:
    job_skills.update(skills)

print("===== TOP 20 REQUIRED JOB SKILLS =====")

for skill, count in job_skills.most_common(20):
    print(skill, ":", count)

===== TOP 20 REQUIRED JOB SKILLS =====
adaptability : 588
relationship building : 267
attention to detail : 253
data analysis : 251
project management : 234
negotiation : 157
sales : 148
presentation skills : 144
business development : 137
financial analysis : 131
strategic thinking : 127
team collaboration : 107
self-motivation : 105
employee relations : 103
financial reporting : 95
flexibility : 92
customer relationship management : 88
creativity : 85
performance management : 83
budgeting : 82

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2)
)

resume_tfidf = tfidf.fit_transform(
    cv_df["processed_resume"].fillna("")
)

print("TF-IDF Resume Matrix Shape:", resume_tfidf.shape)

TF-IDF Resume Matrix Shape: (9544, 5000)

In [25]:
job_tfidf = tfidf.transform(
    job_df["processed_job"].fillna("")
)

print("TF-IDF Job Matrix Shape:", job_tfidf.shape)

TF-IDF Job Matrix Shape: (1167, 5000)

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

# Compare first resume with first job
similarity = cosine_similarity(
    resume_tfidf[0],
    job_tfidf[0]
)

print("Resume-Job Similarity:", similarity[0][0])

Resume-Job Similarity: 0.03765715349831636

In [27]:
print("Existing matching information:")
display(matches_df.head())

Existing matching information:

,candidate_id,job_id,final_score,raw_score,label_strength,semantic_score,skill_score,position_score,category_score,experience_score,education_score,candidate_rank,candidate_rank_pct
0,cand_00000,3906246896,0.635354,0.479077,medium_positive,0.867852,0.215161,0.621538,0.0,0.250,1.0,1,1.000000
1,cand_00000,3902931012,0.599043,0.437020,medium_positive,0.775035,0.000000,0.341304,1.0,0.500,1.0,2,0.977099
2,cand_00000,3905214623,0.560359,0.404657,weak_positive,0.766395,0.054937,0.212903,1.0,0.025,1.0,3,0.923664
3,cand_00000,3889743825,0.540995,0.393352,weak_positive,0.821683,0.000000,0.189655,1.0,0.500,0.5,4,0.885496
4,cand_00000,3902357305,0.538510,0.393074,weak_positive,0.764884,0.046768,0.177419,1.0,0.500,0.5,5,0.877863

In [29]:
from sklearn.metrics.pairwise import cosine_similarity

# Select one resume
resume_index = 0

# Calculate similarity between the selected resume and all jobs
similarity_scores = cosine_similarity(
    resume_tfidf[resume_index],
    job_tfidf
).flatten()

print("Number of similarity scores:", len(similarity_scores))

Number of similarity scores: 1167

In [30]:
ranking_df = pd.DataFrame({
    "job_id": job_df["job_id"],
    "job_title": job_df["job_title"],
    "category": job_df["category"],
    "similarity_score": similarity_scores
})

# Sort from highest to lowest similarity
ranking_df = ranking_df.sort_values(
    by="similarity_score",
    ascending=False
).reset_index(drop=True)

# Add rank
ranking_df.insert(0, "rank", ranking_df.index + 1)

display(ranking_df.head(10))

,rank,job_id,job_title,category,similarity_score
0,1,3906246896,Lead Software Engineer - Finance (Hybrid),FINANCE,0.148568
1,2,3904956273,Staff Data Engineer - People & Finance Tech (R...,FINANCE,0.139897
2,3,3901998589,"VP / Client, Finance & Strategy Data Scientist...",FINANCE,0.129734
3,4,3903867896,"Data Engineer - Enterprise Data and Analytics,...",HR,0.118356
4,5,3895210408,Information Technology Analyst,INFORMATION-TECHNOLOGY,0.117686
5,6,3905214623,Information Technology Support Manager,INFORMATION-TECHNOLOGY,0.114614
6,7,3905354176,Business Development Manager,BUSINESS-DEVELOPMENT,0.114609
7,8,3895527225,Data Solutions Analyst II (Managed Care - Fina...,FINANCE,0.113730
8,9,3902864826,Information Technology Field Technician,INFORMATION-TECHNOLOGY,0.111936
9,10,3889772048,Information Technology Application Manager,INFORMATION-TECHNOLOGY,0.109640

In [31]:
print("===== TOP 10 JOBS FOR SELECTED RESUME =====")

display(
    ranking_df[
        ["rank", "job_id", "job_title", "category", "similarity_score"]
    ].head(10)
)

===== TOP 10 JOBS FOR SELECTED RESUME =====

,rank,job_id,job_title,category,similarity_score
0,1,3906246896,Lead Software Engineer - Finance (Hybrid),FINANCE,0.148568
1,2,3904956273,Staff Data Engineer - People & Finance Tech (R...,FINANCE,0.139897
2,3,3901998589,"VP / Client, Finance & Strategy Data Scientist...",FINANCE,0.129734
3,4,3903867896,"Data Engineer - Enterprise Data and Analytics,...",HR,0.118356
4,5,3895210408,Information Technology Analyst,INFORMATION-TECHNOLOGY,0.117686
5,6,3905214623,Information Technology Support Manager,INFORMATION-TECHNOLOGY,0.114614
6,7,3905354176,Business Development Manager,BUSINESS-DEVELOPMENT,0.114609
7,8,3895527225,Data Solutions Analyst II (Managed Care - Fina...,FINANCE,0.113730
8,9,3902864826,Information Technology Field Technician,INFORMATION-TECHNOLOGY,0.111936
9,10,3889772048,Information Technology Application Manager,INFORMATION-TECHNOLOGY,0.109640

In [32]:
print("===== SELECTED RESUME =====")
print(cv_df.loc[resume_index, "target_position"])

print("\nCandidate ID:")
print(cv_df.loc[resume_index, "candidate_id"])

===== SELECTED RESUME =====
Senior Software Engineer

Candidate ID:
cand_00000

In [33]:
top_job_id = ranking_df.loc[0, "job_id"]

top_job = job_df[job_df["job_id"] == top_job_id].iloc[0]

print("===== BEST MATCH =====")
print("Job Title:", top_job["job_title"])
print("Category:", top_job["category"])
print("Similarity Score:", ranking_df.loc[0, "similarity_score"])

print("\nJob Description:")
print(top_job["job_description"])

===== BEST MATCH =====
Job Title: Lead Software Engineer - Finance (Hybrid)
Category: FINANCE
Similarity Score: 0.1485675505474295

Job Description:
JOB DESCRIPTION

AS A VALUED COLLEAGUE ON OUR TEAM, YOU WILL ACT AS A TEAM LEAD IN THE DESIGNING, PRODUCING, TESTING, OR IMPLEMENTING SOFTWARE, TECHNOLOGY, OR PROCESSES, AS WELL AS LEAD PROCESSES FOR CREATING AND MAINTAINING IT ARCHITECTURE, LARGE SCALE DATA STORES, AND CLOUD-BASED SYSTEMS.

THE IMPACT YOU WILL MAKE

RESPONSIBILITIES

THE LEAD SOFTWARE ENGINEER - FINANCE ROLE WILL OFFER YOU THE FLEXIBILITY TO MAKE EACH DAY YOUR OWN, WHILE WORKING ALONGSIDE PEOPLE WHO CARE SO THAT YOU CAN DELIVER ON THE FOLLOWING RESPONSIBILITIES:

INDEPENDENTLY DETERMINE THE NEEDS OF THE CUSTOMER WHILE IDENTIFYING AND RESOLVING CONFLICTING OR COMPLEMENTARY NEEDS ACROSS CUSTOMER GROUPS.APPLYING ADVANCED SKILL, KNOWLEDGE AND EXPERIENCE, DESIGN AND DEVELOP SOFTWARE SOLUTIONS TO MEET CUSTOMER NEEDS.USE A PROCESS-DRIVEN APPROACH TO LEADING DESIGN SOLUTIONS.IMPLEMENT NEW SOFTWARE TECHNOLOGY AND COORDINATE SIMULTANEOUS IMPLEMENTATION TASKS ACROSS TEAMS.MAY MAINTAIN OR OVERSEE THE MAINTENANCE OF EXISTING SOFTWARE.

QUALIFICATIONS

THE EXPERIENCE YOU BRING TO THE TEAM

MINIMUM REQUIRED EXPERIENCES

4+ YEARS WITH BIG DATA HADOOP CLUSTER (HDFS, YARN, HIVE, MAPREDUCE FRAMEWORKS), SPARK4+ YEARS OF RECENT EXPERIENCE WITH BUILDING AND DEPLOYING APPLICATIONS IN AWS (S3, HIVE, GLUE, AWS BATCH, DYNAMO DB, REDSHIFT, CLOUDWATCH, RDS, LAMBDA, SNS, SWS ETC.)4+ YEARS OF PYTHON, SQL, SPARKSQL, PYSPARKEXCELLENT PROBLEM SOLVING SKILLS AND STRONG VERBAL & WRITTEN COMMUNICATION SKILLSABILITY TO WORK INDEPENDENTLY AS WELL AS PART OF A TEAM

DESIRED EXPERIENCES

BACHELOR DEGREE OR EQUIVALENTKNOWLEDGE OF SPARK STREAMING TECHNOLOGIES FAMILIARITY WITH HADOOP / SPARK INFORMATION ARCHITECTURE, DATA MODELING, MACHINE LEARNING (ML)KNOWLEDGE OF FINANCIAL REPORTING ACCOUNTING SERVICES (FRAS)KNOWLEDGE OF ENTERPRISE DATA MANAGEMENT (EDMCS)EXPERIENCE WITH WORKIVA AND WORKIVA SOX

SKILLS

SKILLED IN CLOUD TECHNOLOGIES AND CLOUD COMPUTINGEXPERIENCE USING SOFTWARE AND COMPUTER SYSTEMS' ARCHITECTURAL PRINCIPLES TO INTEGRATE ENTERPRISE COMPUTER APPLICATIONS SUCH AS XMATTERS, AWS APPLICATION INTEGRATION, OR WEBSPHEREINFLUENCING INCLUDING NEGOTIATING, PERSUADING OTHERS, FACILITATING MEETINGS, AND RESOLVING CONFLICTCOMMUNICATION INCLUDING COMMUNICATING IN WRITING OR VERBALLY, COPYWRITING, PLANNING AND DISTRIBUTING COMMUNICATION, ETC.EXPERIENCE HELPING AN ORGANIZATION TO PLAN AND MANAGE CHANGE IN EFFORT TO MEET STRATEGIC OBJECTIVESWORKING WITH PEOPLE WITH DIFFERENT FUNCTIONAL EXPERTISE RESPECTFULLY AND COOPERATIVELY TO WORK TOWARD A COMMON GOALEXPERTISE IN SERVICE MANAGEMENT CONCEPTS FOR NETWORKS AND RELATED STANDARDS SUCH AS ITIL PRACTICES OR SDLCPROGRAMMING INCLUDING CODING, DEBUGGING, AND USING RELEVANT PROGRAMMING LANGUAGESRELATIONSHIP MANAGEMENT INCLUDING MANAGING AND ENGAGING STAKEHOLDERS, CUSTOMERS, AND VENDORS, BUILDING RELATIONSHIP NETWORKS, CONTRACTING, ETC.OPERATIONAL EXCELLENCE INCLUDING IMPROVING AND OVERSEEING OPERATIONS

TOOLS

JAVAPYTHONAWS

ADDITIONAL INFORMATION

THE FUTURE IS WHAT YOU MAKE IT TO BE. DISCOVER COMPELLING OPPORTUNITIES AT CAREERS.FANNIEMAE.COM.

FANNIE MAE IS AN EQUAL OPPORTUNITY EMPLOYER, WHICH MEANS WE ARE COMMITTED TO FOSTERING A DIVERSE AND INCLUSIVE WORKPLACE. ALL QUALIFIED APPLICANTS WILL RECEIVE CONSIDERATION FOR EMPLOYMENT WITHOUT REGARD TO RACE, RELIGION, NATIONAL ORIGIN, GENDER, GENDER IDENTITY, SEXUAL ORIENTATION, PERSONAL APPEARANCE, PROTECTED VETERAN STATUS, DISABILITY, AGE, OR OTHER LEGALLY PROTECTED STATUS. FOR INDIVIDUALS WITH DISABILITIES WHO WOULD LIKE TO REQUEST AN ACCOMMODATION IN THE APPLICATION PROCESS, EMAIL US AT CAREERS_MAILBOX@FANNIEMAE.COM.

THE HIRING RANGE FOR THIS ROLE IS SET FORTH ON EACH OF OUR JOB POSTINGS LOCATED ON FANNIE MAE'S CAREER SITE. FINAL SALARIES WILL GENERALLY VARY WITHIN THAT RANGE BASED ON FACTORS THAT INCLUDE BUT ARE NOT LIMITED TO, SKILL SET, DEPTH OF EXPERIENCE, CERTIFICATIONS, AND OTHER RELEVANT QUALIFICATIONS. THIS POSITION IS ELIGIBLE TO PARTICIPATE IN A FANNIE MAE INCENTIVE PROGRAM (SUBJECT TO THE TERMS OF THE PROGRAM). AS PART OF OUR COMPREHENSIVE BENEFITS PACKAGE, FANNIE MAE OFFERS A BROAD RANGE OF HEALTH, LIFE, VOLUNTARY LIFESTYLE, AND OTHER BENEFITS AND PERKS THAT ENHANCE AN EMPLOYEE’S PHYSICAL, MENTAL, EMOTIONAL, AND FINANCIAL WELL-BEING. SEE MORE HERE.

PANDOLOGIC. KEYWORDS: SENIOR SOFTWARE ENGINEER, LOCATION: RESTON, VA - 20190

In [34]:
def rank_jobs_for_resume(resume_index, top_n=10):
    
    scores = cosine_similarity(
        resume_tfidf[resume_index],
        job_tfidf
    ).flatten()
    
    result = pd.DataFrame({
        "job_id": job_df["job_id"],
        "job_title": job_df["job_title"],
        "category": job_df["category"],
        "similarity_score": scores
    })
    
    result = result.sort_values(
        "similarity_score",
        ascending=False
    ).reset_index(drop=True)
    
    result.insert(0, "rank", result.index + 1)
    
    return result.head(top_n)

In [35]:
top_jobs = rank_jobs_for_resume(0, 10)

display(top_jobs)

,rank,job_id,job_title,category,similarity_score
0,1,3906246896,Lead Software Engineer - Finance (Hybrid),FINANCE,0.148568
1,2,3904956273,Staff Data Engineer - People & Finance Tech (R...,FINANCE,0.139897
2,3,3901998589,"VP / Client, Finance & Strategy Data Scientist...",FINANCE,0.129734
3,4,3903867896,"Data Engineer - Enterprise Data and Analytics,...",HR,0.118356
4,5,3895210408,Information Technology Analyst,INFORMATION-TECHNOLOGY,0.117686
5,6,3905214623,Information Technology Support Manager,INFORMATION-TECHNOLOGY,0.114614
6,7,3905354176,Business Development Manager,BUSINESS-DEVELOPMENT,0.114609
7,8,3895527225,Data Solutions Analyst II (Managed Care - Fina...,FINANCE,0.113730
8,9,3902864826,Information Technology Field Technician,INFORMATION-TECHNOLOGY,0.111936
9,10,3889772048,Information Technology Application Manager,INFORMATION-TECHNOLOGY,0.109640

In [ ]:
so